MODEL:
  MM:
    BBOX_NECK:
      type: SECONDFPN
      in_channels: [128, 256, 512]
      norm_cfg: 
        type: BN
        eps: 0.001
        momentum: 0.01
      out_channels: [256, 256, 256]
      upsample_cfg: 
        type: deconv
        bias: False
      upsample_strides: [0.5, 1, 2]
      use_conv_for_no_stride: true
