# _BASE_: ["../temporal_single_timeframe.yml", "../models/centerpoint.yml"]
_BASE_: ["../single_timeframe.yml", "../models/centerpoint.yml"]
# _BASE_: ["../single_timeframe.yml", "../models/pointpillar.yml"]

TAG: "lss"
EVA_DIR: "output_dir/lss_mini"
# LOG_DIR: "/work/u5239166/fiery/tensorboard_logs"
# TEST_TRAINSET: True
# EVALUATION: False

GPUS: [1]
EPOCHS: 2
BATCHSIZE: 2
VAL_BATCHSIZE: 2
N_WORKERS: 4
VALID_FREQ: 1.0
GRAD_NORM_CLIP: 10
CKPT_PATH: null

SEMANTIC_SEG:
  NUSCENE_CLASS: False

DATASET:
  DATAROOT: "/home/master/10/cytseng/data/sets/nuscenes/"
  FILTER_INVISIBLE_VEHICLES: True
  VERSION: "v1.0-mini"
  TRAINING_SAMPLES: -1
  VALIDATING_SAMPLES: -1

LOSS: 
  SEG_LOSS_WEIGHT: 
    ALL: 0.2
  OBJ_LOSS_WEIGHT:
    ALL: 0.8

# LIFT:
#   X_BOUND: [-50.0, 50.0, 0.25] #  Forwards
#   Y_BOUND: [-50.0, 50.0, 0.25] # Sides
#   Z_BOUND: [-10.0, 10.0, 20.0] # Height

IMAGE:
  N_CAMERA: 6
  # FINAL_DIM: [256, 704]
  # RESIZE_SCALE: 0.44
  # TOP_CROP: 140
  FINAL_DIM: [512, 1408]
  RESIZE_SCALE: 0.88
  TOP_CROP: 280
  IMAGE_AUG: False

LOSS:
  SEG_USE: False

OBJ:
  HEAD_NAME: "mm"
